language: generic 
sudo: required 
service:
  - docker

before_install:
  - docker build -t atbr/docker-react -f Dockerfile.dev .


script:
  - docker run -e CI=true atbr/docker-react npm run test -- --coverage