language: generic 
sudo: required 
service:
  - docker

before_install:
  - docker build -t atbr/docker-react -f Dockerfile.dev .


script:
  - docker run -e CI=true atbr/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker-react"
  env: "Dockerreact-env-2"
  bucket_name: "elasticbeanstalk-us-east-2-971759180767"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY